import type { ComponentType } from 'react';
import {
  PhoneIcon,
  RentIcon,
  WaterIcon,
  ElectricityIcon,
  GasIcon,
  InternetIcon,
  HouseInsuranceIcon,
  EatingOutIcon,
  TakeAwayIcon,
  TeaCoffeeIcon,
  FastFoodIcon,
  SnacksIcon,
  SwiggyIcon,
  ZomatoIcon,
  UberIcon,
  RapidoIcon,
  AutoIcon,
  CabIcon,
  TrainIcon,
  MetroIcon,
  BusIcon,
  ClothesIcon,
  FootwearIcon,
  ElectronicsIcon,
  FestivalIcon,
  VideoGamesIcon,
  BooksIcon,
  StaplesIcon,
  VegetablesIcon,
  FruitsIcon,
  MeatIcon,
  EggsIcon,
  BakeryIcon,
  EssentialsIcon,
  ToiletriesIcon,
  DecorIcon,
  CleaningIcon,
  MutualFundsIcon,
  StocksIcon,
  IPOIcon,
  PPFIcon,
  NPSIcon,
  FixedDepositIcon,
  ParentsIcon,
  SpouseIcon,
  MomIcon,
  DadIcon,
  PocketMoneyIcon,
  NetflixIcon,
  PrimeIcon,
  YoutubeIcon,
  SoftwareIcon,
  NewsIcon,
  EMIElectronicsIcon,
  HouseEMIIcon,
  VehicleEMIIcon,
  EducationEMIIcon,
  CreditCardIcon,
  HealthInsuranceIcon,
  CarInsuranceIcon,
  LifeInsuranceIcon,
  EntertainmentIcon,
  MoviesIcon,
  ConcertIcon,
  EventsIcon,
  TravelIcon,
  MedicalIcon,
  PersonalIcon,
  FitnessIcon,
  ServicesIcon,
  TaxIcon,
  TopUpIcon,
  ChildrenIcon,
  PetCareIcon,
  BusinessIcon,
  SelfTransferIcon,
  SavingIcon,
  GiftIcon,
  LentIcon,
  DonationIcon,
  HiddenChargesIcon,
  CashWithdrawalIcon,
  ReturnIcon,
  OthersIcon,
  EarningsIcon,
  SalaryIcon,
  BorrowedIcon,
  InterestIcon,
  RedemptionIcon,
  CashDepositIcon,
  DividendsIcon,
  CashbackIcon,
} from './tag-icons';

interface IconProps {
  size?: number;
  color?: string;
}

export interface TagSubItem {
  id: string;
  label: string;
  Icon: ComponentType<IconProps>;
}

/** Category applies to credit, debit, or both transaction types */
export type CategoryType = 'credit' | 'debit' | 'both';

export interface TagCategory {
  id: string;
  label: string;
  description: string;
  Icon: ComponentType<IconProps>;
  /** When omitted, treated as 'debit' for backward compatibility */
  categoryType?: CategoryType;
  subItems: TagSubItem[];
}

export const TAG_CATEGORIES: TagCategory[] = [
  // ─── Credit (income) categories ───────────────────────────────────────────
  {
    id: 'credit_earnings',
    label: 'Earnings',
    description: 'Bonus, commission, freelance income',
    Icon: EarningsIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_earnings.bonus', label: 'Bonus', Icon: EarningsIcon },
      { id: 'credit_earnings.commission', label: 'Commission', Icon: OthersIcon },
      { id: 'credit_earnings.freelance', label: 'Freelance', Icon: OthersIcon },
      { id: 'credit_earnings.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_salary',
    label: 'Salary',
    description: 'Monthly salary and arrears',
    Icon: SalaryIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_salary.monthly', label: 'Monthly', Icon: SalaryIcon },
      { id: 'credit_salary.bonus', label: 'Bonus', Icon: OthersIcon },
      { id: 'credit_salary.arrears', label: 'Arrears', Icon: OthersIcon },
      { id: 'credit_salary.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_pocket_money',
    label: 'Pocket Money',
    description: 'Allowance and pocket money received',
    Icon: PocketMoneyIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_pocket_money.allowance', label: 'Allowance', Icon: PocketMoneyIcon },
      { id: 'credit_pocket_money.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_self_transfer',
    label: 'Self Transfer',
    description: 'Transfer from own account',
    Icon: SelfTransferIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_self_transfer.bank_to_bank', label: 'Bank to bank', Icon: SelfTransferIcon },
      { id: 'credit_self_transfer.from_wallet', label: 'From wallet', Icon: OthersIcon },
      { id: 'credit_self_transfer.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_gift',
    label: 'Gift',
    description: 'Gifts and presents received',
    Icon: GiftIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_gift.birthday', label: 'Birthday', Icon: GiftIcon },
      { id: 'credit_gift.wedding', label: 'Wedding', Icon: OthersIcon },
      { id: 'credit_gift.festival', label: 'Festival', Icon: FestivalIcon },
      { id: 'credit_gift.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_borrowed',
    label: 'Borrowed',
    description: 'Money received as loan',
    Icon: BorrowedIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_borrowed.family', label: 'From family', Icon: ParentsIcon },
      { id: 'credit_borrowed.friend', label: 'From friend', Icon: OthersIcon },
      { id: 'credit_borrowed.loan', label: 'Loan received', Icon: OthersIcon },
      { id: 'credit_borrowed.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_refund',
    label: 'Refund',
    description: 'Refunds and reversals',
    Icon: ReturnIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_refund.purchase', label: 'Purchase refund', Icon: ReturnIcon },
      { id: 'credit_refund.subscription', label: 'Subscription', Icon: OthersIcon },
      { id: 'credit_refund.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_interest',
    label: 'Interest',
    description: 'Interest earned',
    Icon: InterestIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_interest.savings', label: 'Savings', Icon: InterestIcon },
      { id: 'credit_interest.fd', label: 'FD', Icon: FixedDepositIcon },
      { id: 'credit_interest.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_redemption',
    label: 'Redemption',
    description: 'Investment redemption',
    Icon: RedemptionIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_redemption.mutual_fund', label: 'Mutual fund', Icon: MutualFundsIcon },
      { id: 'credit_redemption.fd', label: 'FD', Icon: FixedDepositIcon },
      { id: 'credit_redemption.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_cash_deposit',
    label: 'Cash Deposit',
    description: 'Cash deposited to account',
    Icon: CashDepositIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_cash_deposit.atm', label: 'ATM', Icon: CashDepositIcon },
      { id: 'credit_cash_deposit.bank_counter', label: 'Bank counter', Icon: OthersIcon },
      { id: 'credit_cash_deposit.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_dividends',
    label: 'Dividends',
    description: 'Dividend income',
    Icon: DividendsIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_dividends.stocks', label: 'Stocks', Icon: StocksIcon },
      { id: 'credit_dividends.mutual_fund', label: 'Mutual fund', Icon: MutualFundsIcon },
      { id: 'credit_dividends.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_cashback',
    label: 'Cashback',
    description: 'Cashback received',
    Icon: CashbackIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_cashback.credit_card', label: 'Credit card', Icon: CreditCardIcon },
      { id: 'credit_cashback.wallet', label: 'Wallet', Icon: OthersIcon },
      { id: 'credit_cashback.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_misc',
    label: 'Misc',
    description: 'Other credit income',
    Icon: OthersIcon,
    categoryType: 'credit',
    subItems: [
      { id: 'credit_misc.uncategorized', label: 'Uncategorized', Icon: OthersIcon },
      { id: 'credit_misc.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  // ─── Debit (expense) categories ───────────────────────────────────────────
  {
    id: 'bill',
    label: 'Bill',
    description: 'Rent, Wi-fi, electricity and other bills',
    Icon: ElectricityIcon,
    subItems: [
      { id: 'bill.phone', label: 'Phone', Icon: PhoneIcon },
      { id: 'bill.rent', label: 'Rent', Icon: RentIcon },
      { id: 'bill.water', label: 'Water', Icon: WaterIcon },
      { id: 'bill.electricity', label: 'Electricity', Icon: ElectricityIcon },
      { id: 'bill.gas', label: 'Gas', Icon: GasIcon },
      { id: 'bill.internet', label: 'Internet', Icon: InternetIcon },
      { id: 'bill.house_insurance', label: 'House', Icon: HouseInsuranceIcon },
      { id: 'bill.maintenance', label: 'Maintenance', Icon: OthersIcon },
      { id: 'bill.dth', label: 'DTH / Cable', Icon: OthersIcon },
      { id: 'bill.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'food_drinks',
    label: 'Food & Drinks',
    description: 'Eating out, Swiggy, Zomato etc.',
    Icon: EatingOutIcon,
    subItems: [
      { id: 'food.eating_out', label: 'Eating out', Icon: EatingOutIcon },
      { id: 'food.take_away', label: 'Take Away', Icon: TakeAwayIcon },
      { id: 'food.tea_coffee', label: 'Tea & Coffee', Icon: TeaCoffeeIcon },
      { id: 'food.fast_food', label: 'Fast Food', Icon: FastFoodIcon },
      { id: 'food.snacks', label: 'Snacks', Icon: SnacksIcon },
      { id: 'food.swiggy', label: 'Swiggy', Icon: SwiggyIcon },
      { id: 'food.zomato', label: 'Zomato', Icon: ZomatoIcon },
      { id: 'food.alcohol', label: 'Alcohol', Icon: OthersIcon },
      { id: 'food.groceries_drinks', label: 'Beverages', Icon: OthersIcon },
      { id: 'food.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'transport',
    label: 'Transport',
    description: 'Uber, Ola and other modes of transport',
    Icon: CabIcon,
    subItems: [
      { id: 'transport.uber', label: 'Uber', Icon: UberIcon },
      { id: 'transport.rapido', label: 'Rapido', Icon: RapidoIcon },
      { id: 'transport.auto', label: 'Auto', Icon: AutoIcon },
      { id: 'transport.cab', label: 'Cab', Icon: CabIcon },
      { id: 'transport.train', label: 'Train', Icon: TrainIcon },
      { id: 'transport.metro', label: 'Metro', Icon: MetroIcon },
      { id: 'transport.bus', label: 'Bus', Icon: BusIcon },
      { id: 'transport.fuel', label: 'Fuel', Icon: OthersIcon },
      { id: 'transport.parking', label: 'Parking', Icon: OthersIcon },
      { id: 'transport.toll', label: 'Toll', Icon: OthersIcon },
      { id: 'transport.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'shopping',
    label: 'Shopping',
    description: 'Clothes, shoes, furniture etc.',
    Icon: ClothesIcon,
    subItems: [
      { id: 'shopping.clothes', label: 'Clothes', Icon: ClothesIcon },
      { id: 'shopping.footwear', label: 'Footwear', Icon: FootwearIcon },
      { id: 'shopping.electronics', label: 'Electronics', Icon: ElectronicsIcon },
      { id: 'shopping.festival', label: 'Festival', Icon: FestivalIcon },
      { id: 'shopping.video_games', label: 'Video games', Icon: VideoGamesIcon },
      { id: 'shopping.books', label: 'Books', Icon: BooksIcon },
      { id: 'shopping.accessories', label: 'Accessories', Icon: OthersIcon },
      { id: 'shopping.furniture', label: 'Furniture', Icon: OthersIcon },
      { id: 'shopping.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'groceries',
    label: 'Groceries',
    description: 'Kitchen and other household supplies',
    Icon: StaplesIcon,
    subItems: [
      { id: 'grocery.staples', label: 'Staples', Icon: StaplesIcon },
      { id: 'grocery.vegetables', label: 'Vegetables', Icon: VegetablesIcon },
      { id: 'grocery.fruits', label: 'Fruits', Icon: FruitsIcon },
      { id: 'grocery.meat', label: 'Meat', Icon: MeatIcon },
      { id: 'grocery.eggs', label: 'Eggs', Icon: EggsIcon },
      { id: 'grocery.bakery', label: 'Bakery', Icon: BakeryIcon },
      { id: 'grocery.dairy', label: 'Dairy', Icon: OthersIcon },
      { id: 'grocery.frozen', label: 'Frozen', Icon: OthersIcon },
      { id: 'grocery.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'home',
    label: 'Home',
    description: 'Household related expenses',
    Icon: EssentialsIcon,
    subItems: [
      { id: 'home.essentials', label: 'Essentials', Icon: EssentialsIcon },
      { id: 'home.toiletries', label: 'Toiletries', Icon: ToiletriesIcon },
      { id: 'home.decor', label: 'Decor', Icon: DecorIcon },
      { id: 'home.cleaning', label: 'Cleaning', Icon: CleaningIcon },
      { id: 'home.repairs', label: 'Repairs', Icon: OthersIcon },
      { id: 'home.appliances', label: 'Appliances', Icon: OthersIcon },
      { id: 'home.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'entertainment',
    label: 'Entertainment',
    description: 'Movies, concerts and leisure',
    Icon: EntertainmentIcon,
    subItems: [
      { id: 'entertainment.movies', label: 'Movies', Icon: MoviesIcon },
      { id: 'entertainment.concert', label: 'Concert', Icon: ConcertIcon },
      { id: 'entertainment.gaming', label: 'Gaming', Icon: VideoGamesIcon },
      { id: 'entertainment.theatre', label: 'Theatre', Icon: OthersIcon },
      { id: 'entertainment.sports_event', label: 'Sports event', Icon: OthersIcon },
      { id: 'entertainment.hobby', label: 'Hobby', Icon: OthersIcon },
      { id: 'entertainment.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'events',
    label: 'Events',
    description: 'Weddings, parties and celebrations',
    Icon: EventsIcon,
    subItems: [
      { id: 'events.wedding', label: 'Wedding', Icon: EventsIcon },
      { id: 'events.birthday', label: 'Birthday', Icon: OthersIcon },
      { id: 'events.party', label: 'Party', Icon: OthersIcon },
      { id: 'events.festival', label: 'Festival', Icon: FestivalIcon },
      { id: 'events.conference', label: 'Conference', Icon: OthersIcon },
      { id: 'events.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    description: 'Flights, hotels and trips',
    Icon: TravelIcon,
    subItems: [
      { id: 'travel.flights', label: 'Flights', Icon: TravelIcon },
      { id: 'travel.hotels', label: 'Hotels', Icon: OthersIcon },
      { id: 'travel.vacation', label: 'Vacation', Icon: OthersIcon },
      { id: 'travel.travel_insurance', label: 'Travel insurance', Icon: OthersIcon },
      { id: 'travel.visa', label: 'Visa', Icon: OthersIcon },
      { id: 'travel.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'medical',
    label: 'Medical',
    description: 'Doctor, pharmacy and healthcare',
    Icon: MedicalIcon,
    subItems: [
      { id: 'medical.doctor', label: 'Doctor', Icon: MedicalIcon },
      { id: 'medical.pharmacy', label: 'Pharmacy', Icon: OthersIcon },
      { id: 'medical.hospital', label: 'Hospital', Icon: OthersIcon },
      { id: 'medical.lab_tests', label: 'Lab tests', Icon: OthersIcon },
      { id: 'medical.dental', label: 'Dental', Icon: OthersIcon },
      { id: 'medical.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'personal',
    label: 'Personal',
    description: 'Personal care and grooming',
    Icon: PersonalIcon,
    subItems: [
      { id: 'personal.grooming', label: 'Grooming', Icon: PersonalIcon },
      { id: 'personal.salon', label: 'Salon', Icon: OthersIcon },
      { id: 'personal.spa', label: 'Spa', Icon: OthersIcon },
      { id: 'personal.cosmetics', label: 'Cosmetics', Icon: ToiletriesIcon },
      { id: 'personal.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'fitness',
    label: 'Fitness',
    description: 'Gym, sports and wellness',
    Icon: FitnessIcon,
    subItems: [
      { id: 'fitness.gym', label: 'Gym', Icon: FitnessIcon },
      { id: 'fitness.sports', label: 'Sports', Icon: OthersIcon },
      { id: 'fitness.yoga', label: 'Yoga', Icon: OthersIcon },
      { id: 'fitness.supplements', label: 'Supplements', Icon: OthersIcon },
      { id: 'fitness.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'services',
    label: 'Services',
    description: 'Professional and utility services',
    Icon: ServicesIcon,
    subItems: [
      { id: 'services.plumber', label: 'Plumber', Icon: ServicesIcon },
      { id: 'services.electrician', label: 'Electrician', Icon: OthersIcon },
      { id: 'services.cleaning', label: 'Cleaning', Icon: CleaningIcon },
      { id: 'services.laundry', label: 'Laundry', Icon: OthersIcon },
      { id: 'services.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'subscription',
    label: 'Subscription',
    description: 'Recurring payment to online services',
    Icon: NetflixIcon,
    subItems: [
      { id: 'sub.netflix', label: 'Netflix', Icon: NetflixIcon },
      { id: 'sub.prime', label: 'Prime', Icon: PrimeIcon },
      { id: 'sub.youtube', label: 'YouTube', Icon: YoutubeIcon },
      { id: 'sub.software', label: 'Software', Icon: SoftwareIcon },
      { id: 'sub.news', label: 'News', Icon: NewsIcon },
      { id: 'sub.music', label: 'Music', Icon: OthersIcon },
      { id: 'sub.cloud_storage', label: 'Cloud storage', Icon: OthersIcon },
      { id: 'sub.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'emi',
    label: 'EMI',
    description: 'Repayment of Loan',
    Icon: HouseEMIIcon,
    subItems: [
      { id: 'emi.electronics', label: 'Electronics', Icon: EMIElectronicsIcon },
      { id: 'emi.house', label: 'House', Icon: HouseEMIIcon },
      { id: 'emi.vehicle', label: 'Vehicle', Icon: VehicleEMIIcon },
      { id: 'emi.education', label: 'Education', Icon: EducationEMIIcon },
      { id: 'emi.personal_loan', label: 'Personal loan', Icon: OthersIcon },
      { id: 'emi.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'credit_bill',
    label: 'Credit Bill',
    description: 'Credit Card & BNPL services settlement',
    Icon: CreditCardIcon,
    subItems: [
      { id: 'credit.credit_card', label: 'Credit card', Icon: CreditCardIcon },
      { id: 'credit.bnpl', label: 'BNPL', Icon: OthersIcon },
      { id: 'credit.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'investment',
    label: 'Investment',
    description: 'Money put towards investment',
    Icon: MutualFundsIcon,
    subItems: [
      { id: 'invest.mutual_funds', label: 'Mutual Funds', Icon: MutualFundsIcon },
      { id: 'invest.stocks', label: 'Stocks', Icon: StocksIcon },
      { id: 'invest.ipo', label: 'IPO', Icon: IPOIcon },
      { id: 'invest.ppf', label: 'PPF', Icon: PPFIcon },
      { id: 'invest.nps', label: 'NPS', Icon: NPSIcon },
      { id: 'invest.fixed_deposit', label: 'Fixed Deposit', Icon: FixedDepositIcon },
      { id: 'invest.gold', label: 'Gold', Icon: OthersIcon },
      { id: 'invest.crypto', label: 'Crypto', Icon: OthersIcon },
      { id: 'invest.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'support',
    label: 'Support',
    description: 'Financial support for loved ones',
    Icon: ParentsIcon,
    subItems: [
      { id: 'support.parents', label: 'Parents', Icon: ParentsIcon },
      { id: 'support.spouse', label: 'Spouse', Icon: SpouseIcon },
      { id: 'support.mom', label: 'Mom', Icon: MomIcon },
      { id: 'support.dad', label: 'Dad', Icon: DadIcon },
      { id: 'support.pocket_money', label: 'Pocket Money', Icon: PocketMoneyIcon },
      { id: 'support.family', label: 'Family', Icon: OthersIcon },
      { id: 'support.friends', label: 'Friends', Icon: OthersIcon },
      { id: 'support.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'insurance',
    label: 'Insurance',
    description: 'Payment towards insurance premiums',
    Icon: HealthInsuranceIcon,
    subItems: [
      { id: 'insurance.health', label: 'Health', Icon: HealthInsuranceIcon },
      { id: 'insurance.car', label: 'Vehicle', Icon: CarInsuranceIcon },
      { id: 'insurance.life', label: 'Life', Icon: LifeInsuranceIcon },
      { id: 'insurance.home', label: 'Home', Icon: HouseInsuranceIcon },
      { id: 'insurance.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'tax',
    label: 'Tax',
    description: 'Income tax, GST and other taxes',
    Icon: TaxIcon,
    subItems: [
      { id: 'tax.income_tax', label: 'Income tax', Icon: TaxIcon },
      { id: 'tax.gst', label: 'GST', Icon: OthersIcon },
      { id: 'tax.property_tax', label: 'Property tax', Icon: OthersIcon },
      { id: 'tax.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'top_up',
    label: 'Top Up',
    description: 'Wallet and recharge',
    Icon: TopUpIcon,
    subItems: [
      { id: 'top_up.mobile', label: 'Mobile recharge', Icon: TopUpIcon },
      { id: 'top_up.wallet', label: 'Wallet', Icon: OthersIcon },
      { id: 'top_up.dth', label: 'DTH', Icon: OthersIcon },
      { id: 'top_up.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'children',
    label: 'Children',
    description: 'Kids education and expenses',
    Icon: ChildrenIcon,
    subItems: [
      { id: 'children.education', label: 'Education', Icon: EducationEMIIcon },
      { id: 'children.school_fees', label: 'School fees', Icon: OthersIcon },
      { id: 'children.toys', label: 'Toys', Icon: OthersIcon },
      { id: 'children.activities', label: 'Activities', Icon: OthersIcon },
      { id: 'children.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'pet_care',
    label: 'Pet Care',
    description: 'Pet food, vet and grooming',
    Icon: PetCareIcon,
    subItems: [
      { id: 'pet.food', label: 'Pet food', Icon: PetCareIcon },
      { id: 'pet.vet', label: 'Vet', Icon: MedicalIcon },
      { id: 'pet.grooming', label: 'Grooming', Icon: OthersIcon },
      { id: 'pet.accessories', label: 'Accessories', Icon: OthersIcon },
      { id: 'pet.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'business',
    label: 'Business',
    description: 'Business and work expenses',
    Icon: BusinessIcon,
    subItems: [
      { id: 'business.supplies', label: 'Supplies', Icon: BusinessIcon },
      { id: 'business.tools', label: 'Tools', Icon: OthersIcon },
      { id: 'business.office', label: 'Office', Icon: OthersIcon },
      { id: 'business.client_entertainment', label: 'Client entertainment', Icon: OthersIcon },
      { id: 'business.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'misc',
    label: 'Misc',
    description: 'Miscellaneous expenses',
    Icon: OthersIcon,
    subItems: [
      { id: 'misc.uncategorized', label: 'Uncategorized', Icon: OthersIcon },
      { id: 'misc.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'self_transfer',
    label: 'Self Transfer',
    description: 'Transfer between own accounts',
    Icon: SelfTransferIcon,
    subItems: [
      { id: 'self_transfer.bank_to_bank', label: 'Bank to bank', Icon: SelfTransferIcon },
      { id: 'self_transfer.to_wallet', label: 'To wallet', Icon: OthersIcon },
      { id: 'self_transfer.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'saving',
    label: 'Saving',
    description: 'Savings and deposits',
    Icon: SavingIcon,
    subItems: [
      { id: 'saving.recurring', label: 'Recurring deposit', Icon: SavingIcon },
      { id: 'saving.piggy_bank', label: 'Piggy bank', Icon: OthersIcon },
      { id: 'saving.goal', label: 'Goal', Icon: OthersIcon },
      { id: 'saving.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'gift',
    label: 'Gift',
    description: 'Gifts and presents',
    Icon: GiftIcon,
    subItems: [
      { id: 'gift.birthday', label: 'Birthday', Icon: GiftIcon },
      { id: 'gift.wedding', label: 'Wedding', Icon: OthersIcon },
      { id: 'gift.festival', label: 'Festival', Icon: FestivalIcon },
      { id: 'gift.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'lent',
    label: 'Lent',
    description: 'Money lent to others',
    Icon: LentIcon,
    subItems: [
      { id: 'lent.family', label: 'Family', Icon: LentIcon },
      { id: 'lent.friends', label: 'Friends', Icon: OthersIcon },
      { id: 'lent.colleague', label: 'Colleague', Icon: OthersIcon },
      { id: 'lent.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'donation',
    label: 'Donation',
    description: 'Charity and donations',
    Icon: DonationIcon,
    subItems: [
      { id: 'donation.charity', label: 'Charity', Icon: DonationIcon },
      { id: 'donation.ngo', label: 'NGO', Icon: OthersIcon },
      { id: 'donation.religious', label: 'Religious', Icon: OthersIcon },
      { id: 'donation.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'hidden_charges',
    label: 'Hidden Charges',
    description: 'Fees and hidden charges',
    Icon: HiddenChargesIcon,
    subItems: [
      { id: 'hidden_charges.bank_fee', label: 'Bank fee', Icon: HiddenChargesIcon },
      { id: 'hidden_charges.late_fee', label: 'Late fee', Icon: OthersIcon },
      { id: 'hidden_charges.forex_fee', label: 'Forex fee', Icon: OthersIcon },
      { id: 'hidden_charges.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'cash_withdrawal',
    label: 'Cash Withdrawal',
    description: 'ATM and cash withdrawal',
    Icon: CashWithdrawalIcon,
    subItems: [
      { id: 'cash.atm', label: 'ATM', Icon: CashWithdrawalIcon },
      { id: 'cash.bank_counter', label: 'Bank counter', Icon: OthersIcon },
      { id: 'cash.others', label: 'Others', Icon: OthersIcon },
    ],
  },
  {
    id: 'return',
    label: 'Return',
    description: 'Refunds and returns',
    Icon: ReturnIcon,
    subItems: [
      { id: 'return.purchase', label: 'Purchase return', Icon: ReturnIcon },
      { id: 'return.refund', label: 'Refund', Icon: OthersIcon },
      { id: 'return.cashback', label: 'Cashback', Icon: OthersIcon },
      { id: 'return.others', label: 'Others', Icon: OthersIcon },
    ],
  },
];

export const MOST_USED_TAG_IDS = [
  'food.eating_out',
  'food.take_away',
  'food.fast_food',
  'transport.uber',
  'transport.auto',
];

export const MOST_USED_TAG_IDS_CREDIT = [
  'credit_salary.monthly',
  'credit_self_transfer.bank_to_bank',
  'credit_gift.birthday',
  'credit_refund.purchase',
  'credit_interest.savings',
];

/** Returns categories that apply to the given transaction type (credit or debit). */
export function getCategoriesForTransactionType(
  transactionType: 'credit' | 'debit'
): TagCategory[] {
  return TAG_CATEGORIES.filter(cat => {
    const type = cat.categoryType ?? 'debit';
    return type === transactionType || type === 'both';
  });
}

export function findTagSubItem(id: string): TagSubItem | undefined {
  for (const cat of TAG_CATEGORIES) {
    const found = cat.subItems.find(s => s.id === id);
    if (found) return found;
  }
  return undefined;
}

export function findTagCategory(subItemId: string): TagCategory | undefined {
  return TAG_CATEGORIES.find(cat => cat.subItems.some(s => s.id === subItemId));
}
